module.exports = {
    //System related errors
    E0000: "An unhandled exception occurred.",

    E0001: "Organization or employee does not exist",
    E0002: "Invalid user credentials",
    E0003: "Failed to update password token",
    E0004: "Device does not exist",
    E0005: "Failed to update the device details",
    E0006: "Invalid parameters",
    E0007: "Failed to update the user details",
    E0008: "Failed to update the organization details",
    E0009: "Failed to update user",
    E0010: "Email already exists",
    E0011: "Failed to add store",
    E0012: "No store exists",
    E0013: "Failed to update user survey",
    E0014: "User not exists",
    E0015: "Failed to fetch survey",
    E0016: "No user exists with email {0}",
    E0017: "Failed to update user",
    E0018: "Event does not exist",
    E0019: "Event does not exist",
    E0020: "Failed to insert claim",
    E0021: "None of such activities are recorded for this category",
    E0022: "Failed to fetch device type",
    E0023: "Device with given info has already been registered",
    E0024: "Failed to register device",
    E0025: "DeviceType {0} already exists for the organization",
    E0026: "DeviceType {0} already exists in the iot platform",
    E0027: "Device {0} already exists for the organization",
    E0028: "Device {0} already exists in the iot platform",
    E0029: "Failed to fetch device",
    E0030: "Failed to fetch device with deviceId {0}",
    E0031: "No such device exists",
    E0032: "Failed to update configurations",
    E0033: "Failed to fetch user with {0}",
    E0034: "No valid data payload",
    E0035: "Failed to update the device data",
    E0036: "Failed to delete the push token",
    E0037: "Failed to contact gateway",
    E0038: "No device is assigned",
    E0039: "Failed to update the device Id",
    E0040: "Failed to assign the device",
    E0041: "Device is in improper state",
    E0042: "Failed to update the device status",

    E1001: "No user exists with the corresponding user id",
    E1002: "Failed to update the document",
    E1003: "No user registered with given token in the system",

    E1004: "No user exists with given credentials",
    E1005: "Failed to update the device token",
    E1006: "Invalid patient email",
    E1007: "No patient exists with given patient id",
    E1008: "Invalid user identifier",
    E1009: "Failed to create a user with {0}",
    E1010: "Failed to update a patient with a caretaker",
    E1011: "Invalid device type",
    E1012: "Invalid device ID",
    E1013: "Failed to update the device details",
    E1014: "No device registered with device ID {0}",
    E1015: "No patient registered with patientId {0}",
    E1016: "Invalid message type",
    E1017: "No user exists with given user id {0}",
    E1018: "Failed to update the server",
    E1019: "Invalid patient id",
    E1020: "Invalid medication id",
    E1021: "Invalid date range",
    E1022: "FSBL with {0} already registered",
    E1023: "Invalid user id",
    E1024: "Failed to update user preferences",
    E1025: "Invalid device token",
    E1026: "Invalid device type",
    E1027: "Failed to update user push token",
    E1028: "Failed to retrieve notifications",
    E1029: "Invalid wifi name",
    E1030: "Invalid wifi password",
    E1031: "No device exist for a given patient",
    E1032: "Failed to configure wifi for the smart communicator",
    E1033: "No given fsbl assigned to given patient",
    E1034: "Failed to register given fsbl to the smart communicator",
    E1035: "Invalid fsbl id",
    E1036: "No device registered with given mac address in foundation",
    E1037: "No device registered with given mac address in system",
    E1038: "No valid token exist in the request",
    E1039: "Error in generating token",
    E1040: "No such token registered in system",
    E1041: "Invalid user type",
    E1042: "Invalid timestamp",
    E1043: "Invalid slot",
    E1044: "The device of id {0} is not allowed to register",
    E1045: "Failed to load the excel",
    E1046: "Excel is not in correct format",
    E1047: "A medication schedule with the file number {0} already exists",
    E1048: "The smart connector of {0} and fsbl of {1} belongs different patients",
    E1049: "Failed to update user password",
    E1050: "No user exists with email {0}",

    E1052: "Failed to update profile image",
    E1053: "Failed to register patient wellness",
    E1054: "Failed to retrieve geocoding for the user's address",
    E1055: "Invalid ifttt token",
    E1056: "Failed to retrieve wellness for the given patient",
    E1057: "Device already exists",
    E1058: "Failed to register real time notification device for this user",
    E1059: "The device has not been assigned to the patient",
    E1060: "Failed to register patient karma",
    E1061: "User not registered",
    E1062: "No patient ID provided for user type patient",

    E2001: "Required parameters are missing. Please refer to the API documentation.",
    E2002: "Failed to add user",
    E2003: "Failed to retrieve user",
    E2004: "Failed to find the user to update",
    E2005: "Failed to send email invite",
    E2006: "Failed to update user with generated activation code",
    E2007: "An activation code has already been sent to this user",
    E2008: "A user has already been registered with this email address",

    E3001: "Failed to add blister details",
    E3002: "Failed to add Medication Schedule",
    E3003: "Failed to update blister details",
    E3004: "Failed to create activity for event",
    E3005: "Failed when creating event document",

    E4001: "Failed to create patients",

    E5001: "Failed to retrieve specified medication schedule",
    E5002: "Failed to retrieve blisters",
    E5003: "Blister has already been consumed",
    E5004: "This slot does not contain any medication",

    E6002: "Failed to retrieve Medication Schedules for this period",
    E6003: "Failed to retrieve medication details for the selected schedules",
    E6004: "Failed to update active medication schedule",

    E7001: "Could not find activities for the given filters",

    E8001: "Schedule Job Name has not been provided",
    E8002: "Schedule time has not been provided",

    E9001: "Could not store personality insight details",
    E9002: "Minimum number of characters is 100"



};
